---
- name: prepare your env
  hosts: docker
  vars:
    - _username: <user>
    - _password: <password>
  become: true
  gather_facts: yes
  handlers:
  - name: restart_sshd
    service:
      name: sshd
      state: restarted
  tasks:
    - name: Fail if user is missing
      ansible.builtin.fail:
        msg: "You need to set username in vars ''{{ _username }}'' is not defined"
      when: _username | length == 0
      
    - name: Create your user "'{{ _username }}'"
      ansible.builtin.user:
        name: '{{ _username }}'
        state: present
        password: '{{ _password }}'
        shell: /bin/bash
      notify: restart_sshd

    - name: Add sudo rights for user
      ansible.builtin.copy:
        dest: /etc/sudoers.d/{{ _username }}
        content: "{{ _username }} ALL=(root) NOPASSWD: ALL"

    - name: Ensure ssh file are in place
      ansible.builtin.file:
        path: /home/{{ _username }}/.ssh
        state: directory
        owner: '{{ _username }}'
        group: '{{ _username }}'
        mode: 0700

    - name: Set authorized key in alternate location
      ansible.posix.authorized_key:
        user: '{{ _username }}'
        state: present
        key: "{{ lookup('file', 'id_rsa.pub') }}"
        path: /home/{{ _username }}/.ssh/authorized_keys
        manage_dir: False
      notify: restart_sshd

    - name: Print out your new IP for your vagrant VM 
      debug: var=ansible_all_ipv4_addresses
